apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbhost-pvc

spec:
  volumeName: dbhost-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi