apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb

    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-vol
          persistentVolumeClaim:
            claimName: dbhost-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
spec:
  selector:
    app: mongodb

  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  type: LoadBalancer
