apiVersion: v1
kind: Service
metadata:
#  unique key for service
  name: fastapi-example

spec:
  ports:
    #    accept traffic send to port 80
    - name: http
      port: 80
      #target port where your app is listens
      targetPort: 80
  selector:
    #Loadbalance traffic across pods matching
    # this label selector
    app: my-webapp-fast

  type:
    LoadBalancer